# Generated by Django 5.1.7 on 2025-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isPrivate',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
