# Generated by Django 5.1.7 on 2025-04-10 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_listing_isprivate_listing_password_listing_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noOfRatings',
            field=models.ManyToManyField(blank=True, related_name='rated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
